### ISSUE TITLE
enable vs enabled

### ISSUE THREAD

**Issue by danhejd** [datagrok/modular-git-hooks#5]
The documentation uses the key "enabled" for configuration but the script only honor "enable".
e.g:
<code>git config --bool hook.pre-commit.d/format-code.sh.enabled false</code>
should be:
<code>git config --bool hook.pre-commit.d/format-code.sh.enable false</code>

This appears in the README.md file as well as in the online documentation.
Thanks for this nice tool!

**Comment by datagrok** [comment]
Yikes! Great find. Sorry for the bug.

I'm working on a fix now. It could be just a two-character patch but I'm concerned about breaking things for users who already use .enable, so I'm trying a slightly more robust approach.

**Comment by datagrok** [comment]
Okay! The dispatch script has been updated to match the README and recognize .enable**d**.

For a while, it will include a feature to automatically migrate `.enable` to `.enabled`, if it can. Support for `.enable` will disappear in the future. Closing this issue, but if you have trouble or it doesn't behave as I describe feel free to re-open.

Thanks again for the report.
